let deck = [
  {card: '2',
  value: 2,
  suit: 'spade',
  image: "card-images/JPEG/2S.jpg",
  played: false},

  {card: '3',
  value: 3,
  suit: 'spade',
  image: "card-images/JPEG/3S.jpg",
  played: false},

  {card: '4',
  value: 4,
  suit: 'spade',
  image: "card-images/JPEG/4S.jpg",
  played: false},

  {card: '5',
  value: 5,
  suit: 'spade',
  image: "card-images/JPEG/5S.jpg",
  played: false},

  {card: '6',
  value: 6,
  suit: 'spade',
  image: "card-images/JPEG/6S.jpg",
  played: false},

  {card: '7',
  value: 7,
  suit: 'spade',
  image: "card-images/JPEG/7S.jpg",
  played: false},

  {card: '8',
  value: 8,
  suit: 'spade',
  image: "card-images/JPEG/8S.jpg",
  played: false},

  {card: '9',
  value: 9,
  suit: 'spade',
  image: "card-images/JPEG/9S.jpg",
  played: false},

  {card: '10',
  value: 10,
  suit: 'spade',
  image: "card-images/JPEG/10S.jpg",
  played: false},

  {card: 'J',
  value: 10,
  suit: 'spade',
  image: "card-images/JPEG/JS.jpg",
  played: false},

  {card: 'Q',
  value: 10,
  suit: 'spade',
  image: "card-images/JPEG/QS.jpg",
  played: false},

  {card: 'K',
  value: 10,
  suit: 'spade',
  image: "card-images/JPEG/KS.jpg",
  played: false},

  {card: 'A',
  value: 11,
  suit: 'spade',
  image: "card-images/JPEG/AS.jpg",
  played: false},


  {card: '2',
  value: 2,
  suit: 'heart',
  image: "card-images/JPEG/2H.jpg",
  played: false},

  {card: '3',
  value: 3,
  suit: 'heart',
  image: "card-images/JPEG/3H.jpg",
  played: false},

  {card: '4',
  value: 4,
  suit: 'heart',
  image: "card-images/JPEG/4H.jpg",
  played: false},

  {card: '5',
  value: 5,
  suit: 'heart',
  image: "card-images/JPEG/5H.jpg",
  played: false},

  {card: '6',
  value: 6,
  suit: 'heart',
  image: "card-images/JPEG/6H.jpg",
  played: false},

  {card: '7',
  value: 7,
  suit: 'heart',
  image: "card-images/JPEG/7H.jpg",
  played: false},

  {card: '8',
  value: 8,
  suit: 'heart',
  image: "card-images/JPEG/8H.jpg",
  played: false},

  {card: '9',
  value: 9,
  suit: 'heart',
  image: "card-images/JPEG/9H.jpg",
  played: false},

  {card: '10',
  value: 10,
  suit: 'heart',
  image: "card-images/JPEG/10H.jpg",
  played: false},

  {card: 'J',
  value: 10,
  suit: 'heart',
  image: "card-images/JPEG/JH.jpg",
  played: false},

  {card: 'Q',
  value: 10,
  suit: 'heart',
  image: "card-images/JPEG/QH.jpg",
  played: false},

  {card: 'K',
  value: 10,
  suit: 'heart',
  image: "card-images/JPEG/KH.jpg",
  played: false},

  {card: 'A',
  value: 11,
  suit: 'heart',
  image: "card-images/JPEG/AH.jpg",
  played: false},


  {card: '2',
  value: 2,
  suit: 'diamond',
  image: "card-images/JPEG/2D.jpg",
  played: false},

  {card: '3',
  value: 3,
  suit: 'diamond',
  image: "card-images/JPEG/3D.jpg",
  played: false},

  {card: '4',
  value: 4,
  suit: 'diamond',
  image: "card-images/JPEG/4D.jpg",
  played: false},

  {card: '5',
  value: 5,
  suit: 'diamond',
  image: "card-images/JPEG/5D.jpg",
  played: false},

  {card: '6',
  value: 6,
  suit: 'diamond',
  image: "card-images/JPEG/6D.jpg",
  played: false},

  {card: '7',
  value: 7,
  suit: 'diamond',
  image: "card-images/JPEG/7D.jpg",
  played: false},

  {card: '8',
  value: 8,
  suit: 'diamond',
  image: "card-images/JPEG/8D.jpg",
  played: false},

  {card: '9',
  value: 9,
  suit: 'diamond',
  image: "card-images/JPEG/9D.jpg",
  played: false},

  {card: '10',
  value: 10,
  suit: 'diamond',
  image: "card-images/JPEG/10D.jpg",
  played: false},

  {card: 'J',
  value: 10,
  suit: 'diamond',
  image: "card-images/JPEG/JD.jpg",
  played: false},

  {card: 'Q',
  value: 10,
  suit: 'diamond',
  image: "card-images/JPEG/QD.jpg",
  played: false},

  {card: 'K',
  value: 10,
  suit: 'diamond',
  image: "card-images/JPEG/KD.jpg",
  played: false},

  {card: 'A',
  value: 11,
  suit: 'diamond',
  image: "card-images/JPEG/AD.jpg",
  played: false},


  {card: '2',
  value: 2,
  suit: 'club',
  image: "card-images/JPEG/2C.jpg",
  played: false},

  {card: '3',
  value: 3,
  suit: 'club',
  image: "card-images/JPEG/3C.jpg",
  played: false},

  {card: '4',
  value: 4,
  suit: 'club',
  image: "card-images/JPEG/4C.jpg",
  played: false},

  {card: '5',
  value: 5,
  suit: 'club',
  image: "card-images/JPEG/5C.jpg",
  played: false},

  {card: '6',
  value: 6,
  suit: 'club',
  image: "card-images/JPEG/6C.jpg",
  played: false},

  {card: '7',
  value: 7,
  suit: 'club',
  image: "card-images/JPEG/7C.jpg",
  played: false},

  {card: '8',
  value: 8,
  suit: 'club',
  image: "card-images/JPEG/8C.jpg",
  played: false},

  {card: '9',
  value: 9,
  suit: 'club',
  image: "card-images/JPEG/9C.jpg",
  played: false},

  {card: '10',
  value: 10,
  suit: 'club',
  image: "card-images/JPEG/10C.jpg",
  played: false},

  {card: 'J',
  value: 10,
  suit: 'club',
  image: "card-images/JPEG/JC.jpg",
  played: false},

  {card: 'Q',
  value: 10,
  suit: 'club',
  image: "card-images/JPEG/QC.jpg",
  played: false},

  {card: 'K',
  value: 10,
  suit: 'club',
  image: "card-images/JPEG/KC.jpg",
  played: false},

  {card: 'A',
  value: 11,
  suit: 'club',
  image: "card-images/JPEG/AC.jpg",
  played: false}
]
